// lgtmoon-frontend/src/App.tsx
import React, { useState } from 'react';
import logo from './logo.svg';
import styled, { createGlobalStyle } from 'styled-components';
import './App.css';
import { RecentImages } from './components/RecentImages';
import { RandomImages } from './components/RandomImages';
import { StaredImages } from './components/StaredImages';
import { Help } from './components/Help';

const AppPage = styled.div`
`

const AppContent = styled.div`
`

const Header = styled.header`
  display: flex;
  flex-direction: column;
`

const TitleComponent = styled.div`
  display: flex;
  flex-direction: row;
  align-items: left;
`

// ikafont の設定が index.css にある
const Title = styled.h1`
  font-family: ikafont;
  margin: 0;
  font-size: 4em;

`

const AppBar = styled.div`
  background-color: #def;
  padding: 5px;
  display: flex;
  flex-direction: row;
  gap: 5px;
`

const TextInput = styled.input`
  box-sizing: border-box;
  height: 28px;
  width: 300px;
  border-width: 0;
`

const ButtonBase = styled.button`
  border: 0;
  background: #009;
  color: #fff;
  font-weight: 700;
  cursor: pointer;
`

const SubmitButton = styled(ButtonBase)`
  height: 28px;
  width: 100px;
`

const UploadButton = styled(ButtonBase)`
  height: 28px;
  width: 200px;
`

const TabGroup = styled.div`
 display: flex;
 flex-direction: row;
 justify-content: space-between;
 width: 100%;
`

const Tab = styled.div`
  cursor: pointer;
  font-weight: 700;
  font-size: 1.5em;
  text-align: center;
  width: 100%;
  padding: 10px 0;

  &:hover {
    background-color: #ccf;
    color: #000;
  }
`

const SelectedTab = styled(Tab)`
  background-color: #009;
  color: #fff;
`

type TabId = "recent"|"random"|"star"|"help"
type TabEntity = {
  id: TabId
  name: string
}

function App() {
  const [tabId, setTabId] = useState<TabId>("recent")
  return (
    <AppPage>
      <AppContent>
        <Header>
          <TitleComponent>
            <Title>LGTMoon</Title>
          </TitleComponent>
          <AppBar>
            <TextInput type="text"></TextInput>
            <SubmitButton>検索</SubmitButton>
            <UploadButton>画像アップロード</UploadButton>
          </AppBar>
          <TabGroup>
            {tabId === "recent" ? <SelectedTab>最近の画像</SelectedTab> : <Tab onClick={e => setTabId("recent")}>最近の画像</Tab>}
            {tabId === "random" ? <SelectedTab>ランダム</SelectedTab> : <Tab onClick={e => setTabId("random")}>ランダム</Tab>}
            {tabId === "star" ? <SelectedTab>お気に入り</SelectedTab> : <Tab onClick={e => setTabId("star")}>お気に入り</Tab>}
            {tabId === "help" ? <SelectedTab>使い方</SelectedTab> : <Tab onClick={e => setTabId("help")}>使い方</Tab>}
          </TabGroup>
        </Header>
        {tabId === "recent" && <RecentImages/>}
        {tabId === "random" && <RandomImages/>}
        {tabId === "star" && <StaredImages/>}
        {tabId === "help" && <Help/>}
      </AppContent>
    </AppPage>
  );
}

export default App;

// frontend/src/App.vue
<template>
  <div class="lgtmoon-app center">
    <Header/>
    <Bar/>
    <div class="menu">
      <div v-on:click="recent()" class="menu-item"
           :class="{ 'menu-item-selected' : selected == 0 }">
        最近の画像
      </div>
      <div v-on:click="random()" class="menu-item"
           :class="{ 'menu-item-selected' : selected == 1 }">
        ランダム
      </div>
      <div v-on:click="help()" class="menu-item"
           :class="{ 'menu-item-selected' : selected == 2 }">
        使い方
      </div>
    </div>
    <Recent v-show="selected == 0"/>
    <Random v-show="selected == 1"/>
    <Help/>
  </div>
</template>

<script>
 import Header from '@/components/Header'
 import Bar from '@/components/Bar'
 import Recent from '@/components/Recent'
 import Random from '@/components/Random'
 import Help from '@/components/Help'

 export default {
     name: 'app',
     data() {
         return {
             selected: 0
         }
     },
     components: {
         Header,
         Bar,
         Recent,
         Random,
         Help
     },
     methods: {
         recent() {
             this.selected = 0
         },
         random() {
             this.selected = 1
         },
         help() {
             this.selected = 2
         }
     }
 }
</script>

<style>
 .lgtmoon-app {
     font-family: 'Avenir', Helvetica, Arial, sans-serif;
     -webkit-font-smoothing: antialiased;
     -moz-osx-font-smoothing: grayscale;
     width: 900px;
     position: relative;
 }
 .center {
    margin-left: auto;
    margin-right: auto;
 }
 .menu:after {
     clear: both;
 }
 .menu-item {
     width: 300px;
     padding: 5px 0px;
     text-align: center;
     vertical-align: middle;
     float: left;
     cursor: pointer;
     font-size: 1.5em;
     font-weight: bold;
     color: #300;
 }
 .menu-item:hover {
     background: #ccf;
     color: #600;
 }
 .menu-item-selected {
     background: #009;
     color: #ffffff;
 }
</style>
